/// Config-exclusive configuration management
//     Copyright (C) 2024  Dustin Thomas <io@cptlobster.dev>
//
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
//
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
//
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <https://www.gnu.org/licenses/>.

use std::collections::HashMap;
use std::fmt::{Display, Formatter, Result as FmtResult};
use serde::{Serialize, Deserialize};
use crate::sway::options::bindsym;
use crate::sway::commands::Runtime;

#[derive(PartialEq, Eq, Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct Config {
    #[serde(default)]
    set: Option<HashMap<String, String>>,
    #[serde(default)]
    exec: Option<Vec<String>>,
    #[serde(default)]
    exec_always: Option<Vec<String>>,
    #[serde(default)]
    bindsym: Option<HashMap<String, KeylessBindsym>>,
}

#[derive(PartialEq, Eq, Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub struct KeylessBindsym {
    #[serde(default)]
    flags: bindsym::BindFlags,
    #[serde(flatten)]
    command: Runtime
}

impl KeylessBindsym {
    pub fn new(flags: bindsym::BindFlags, command: Runtime) -> Self {
        Self { flags, command }
    }
}

fn with_comment_header(section: String, header: String) -> String {
    let comment = header.lines().map(|l| format!("# {l}")).collect::<Vec<String>>().join("\n");
    format!("{}\n{}\n\n", comment, section)
}

fn stringify_sets(sets: &Option<HashMap<String, String>>) -> String {
    match sets {
        Some(s) => {
            if s.is_empty() {String::new()}
            else {
                with_comment_header(s.iter().map(|(k, v)|
                    format!("set ${k} {v}")
                ).collect::<Vec<String>>().join("\n"),
                "Variables (using [set] table)".to_string())
            }
        }
        None => String::new()
    }
}

fn stringify_bindsyms(bindsym: &Option<HashMap<String, KeylessBindsym>>) -> String {
    match bindsym {
        Some(s) => {
            if s.is_empty() {String::new()}
            else {
                with_comment_header(
                    s.iter().map(|(k, KeylessBindsym{flags, command})|
                        format!("bindsym {flags}{k} {command}")
                    ).collect::<Vec<String>>().join("\n"),
                    "User-defined bindsym commands (using [bindsym] table)".to_string()
                )
            }
        }
        None => String::new()
    }
}

fn stringify_exec(exec: &Option<Vec<String>>) -> String {
    match exec {
        Some(s) => {
            if s.is_empty() {String::new()}
            else {
                with_comment_header(
                    s.iter().map(|s| format!("exec {s}")).collect::<Vec<String>>().join("\n"),
                    "Startup commands (using exec array)\
                    \nNote: these will only be run once; NOT when reload is called\
                    \nUse exec-always if you need this command run on reload".to_string()
                )
            }
        }
        None => String::new()
    }
}

fn stringify_exec_always(exec_always: &Option<Vec<String>>) -> String {
    match exec_always {
        Some(s) => {
            if s.is_empty() {String::new()}
            else {
                with_comment_header(
                    s.iter().map(|s| format!("exec-always {s}")).collect::<Vec<String>>().join("\n"),
                    "Startup commands (using exec-always array)\
                    \nNote: these will be run every time that reload is called".to_string())
            }
        }
        None => String::new()
    }
}

impl Display for Config {
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        let header =
            "This configuration was generated by the swayconf configurator.\
            \nPlease note that this program does NOT validate your configuration, you\
            \nwill need to run `sway -c [config file] -C` to do so.\
            \n\
            \nFor more information, please visit https://github.com/cptlobster/swayconf.";
        write!(f, "{}{}{}{}{}",
               with_comment_header(String::new(), header.to_string()),
               stringify_sets(&self.set),
               stringify_exec(&self.exec),
               stringify_exec_always(&self.exec_always),
               stringify_bindsyms(&self.bindsym))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_sway() {
        let mut config = Config::default();
        config.exec = Some(
            vec![
                "ls".to_string(),
                "/bin/bash".to_string(),
            ]
        );

        let mut keys = HashMap::new();
        keys.insert("Mod4+Shift".to_string(), KeylessBindsym::new(bindsym::BindFlags::default(), Runtime::Exec { command: "ls -la ~".to_string() }));
        keys.insert("Mod4+X".to_string(), KeylessBindsym::new(bindsym::BindFlags::default(), Runtime::Exec { command: "~/beans.sh".to_string() }));

        config.bindsym = Some(keys);

        println!("{}", config.to_string());
    }

    #[test]
    fn test_serde() {
        let cfg: Config = toml::from_str(
            "exec = [\"ls\", \"/bin/bash\"]\
            \n\
            \n[set]\
            \nmod = \"Mod4\"\
            \n[bindsym]\
            \n\"$mod+Shift\".exec.command = \"ls -la\"\
            \n\"$mod+X\".exec.command = \"~/beans.sh\""
        ).unwrap();

        println!("{}", cfg.to_string());
    }
}